### ISSUE TITLE
error:unknown

### ISSUE THREAD

**Issue by Weststreet** [neverwoodsS/idea_flutter_json_format#1]
感谢这么好的插件，但是在使用过程中自动生成如下格式的json时提示error:unknown
{
	"code": 200,
	"message": "SUCCESS",
	"data": {
		"pageNum": 0,
		"pageSize": 0,
		"size": 3,
		"orderBy": 5,
		"startRow": 1,
		"endRow": 3,
		"total": 3,
		"pages": 0,
		"list": [{
				"id": 1,
				"cover": "https://images.rapgenius.com/4xo4vvlzcnbsluagktti85tf1.1000x1000x1.jpg",
				"title": "有伴英语第一课",
				"content": "本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有",
				"audio": "https://ia801000.us.archive.org/22/items/MagnaCarta/13.Bbc.mp3",
				"type": 0,
				"audioDuration": 123,
				"createTime": 1550131610000
			},
			{
				"id": 2,
				"cover": "https://images.rapgenius.com/4xo4vvlzcnbsluagktti85tf1.1000x1000x1.jpg",
				"title": "有伴英语第一课",
				"content": "本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有",
				"audio": "https://ia801000.us.archive.org/22/items/MagnaCarta/13.Bbc.mp3",
				"type": 0,
				"audioDuration": 123,
				"createTime": 1550131610000
			},
			{
				"id": 3,
				"cover": "https://images.rapgenius.com/4xo4vvlzcnbsluagktti85tf1.1000x1000x1.jpg",
				"title": "有伴英语第一课",
				"content": "本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有",
				"audio": "https://ia801000.us.archive.org/22/items/MagnaCarta/13.Bbc.mp3",
				"type": 0,
				"audioDuration": 123,
				"createTime": 1550131610000
			}
		],
		"prePage": 0,
		"nextPage": 0,
		"isFirstPage": false,
		"isLastPage": true,
		"hasPreviousPage": false,
		"hasNextPage": false,
		"navigatePages": 8,
		"navigatepageNums": [],
		"navigateFirstPage": 0,
		"navigateLastPage": 0,
		"firstPage": 0,
		"lastPage": 0
	}
}

**Comment by neverwoodsS** [comment]
> 感谢这么好的插件，但是在使用过程中自动生成如下格式的json时提示error:unknown
> {
> "code": 200,
> "message": "SUCCESS",
> "data": {
> "pageNum": 0,
> "pageSize": 0,
> "size": 3,
> "orderBy": 5,
> "startRow": 1,
> "endRow": 3,
> "total": 3,
> "pages": 0,
> "list": [{
> "id": 1,
> "cover": "https://images.rapgenius.com/4xo4vvlzcnbsluagktti85tf1.1000x1000x1.jpg",
> "title": "有伴英语第一课",
> "content": "本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有",
> "audio": "https://ia801000.us.archive.org/22/items/MagnaCarta/13.Bbc.mp3",
> "type": 0,
> "audioDuration": 123,
> "createTime": 1550131610000
> },
> {
> "id": 2,
> "cover": "https://images.rapgenius.com/4xo4vvlzcnbsluagktti85tf1.1000x1000x1.jpg",
> "title": "有伴英语第一课",
> "content": "本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有",
> "audio": "https://ia801000.us.archive.org/22/items/MagnaCarta/13.Bbc.mp3",
> "type": 0,
> "audioDuration": 123,
> "createTime": 1550131610000
> },
> {
> "id": 3,
> "cover": "https://images.rapgenius.com/4xo4vvlzcnbsluagktti85tf1.1000x1000x1.jpg",
> "title": "有伴英语第一课",
> "content": "本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有本课的主要内容有",
> "audio": "https://ia801000.us.archive.org/22/items/MagnaCarta/13.Bbc.mp3",
> "type": 0,
> "audioDuration": 123,
> "createTime": 1550131610000
> }
> ],
> "prePage": 0,
> "nextPage": 0,
> "isFirstPage": false,
> "isLastPage": true,
> "hasPreviousPage": false,
> "hasNextPage": false,
> "navigatePages": 8,
> "navigatepageNums": [],
> "navigateFirstPage": 0,
> "navigateLastPage": 0,
> "firstPage": 0,
> "lastPage": 0
> }
> }

navigatepageNums 数据为空，无法推断类型导致的错误。已修复，请等待下一版发布更新。目前请暂时从 json 中去掉这段数据即可。从名字上看这应该是一个数字数组，手动给数组添加一个数字也是可以解决的。
