### ISSUE TITLE
fromMapList(dynamic mapList) mapList最好做一下非空判断

### ISSUE THREAD

**Issue by BigTimo** [neverwoodsS/idea_flutter_json_format#3]

**Comment by kennenfromchina** [comment]
为什么2.0版本把这个fromMapList给去掉了？

**Comment by neverwoodsS** [comment]
> 为什么2.0版本把这个fromMapList给去掉了？

先说结论：为了精简生成的代码量，以及代码的可靠程度。

fromMapList 在原本的设计中不是拿来让用户在外部使用的，纯粹是一种中间产物，用来实现 List<T> 的映射。

以前是不论这个 fromMapList 是否会被用到，每个 class 都生成一个，然后导致生成的文件过于庞大。
现在是所有的 List 都通过 map 操作符映射出来，且只有在需要的时候才做。

示例：

```dart
testBean.programmers = List()..addAll(
      (map['programmers'] as List ?? []).map((o) => ProgrammersBean.fromMap(o))
);
```

而且，还有另外的朋友提的 issue 中有嵌套 List 类型的需求，为了实现这个效果，代码必须进行重构，原有的 fromMapList 也已不满足需求。
