### ISSUE TITLE
JSON嵌套的数组无法生成

### ISSUE THREAD

**Issue by tanpengsccd** [neverwoodsS/idea_flutter_json_format#5]
如下
```
{
    "jsonrpc": "2.0",
    "method": "aria2.tellActive",
    "id": "QXJpYU5nXzE1NTcwNDE5MzdfMC4xMTk5MDc2NTM4NjM5MTE2Nw==",
    "params": [
        [
            "completedLength",
            "connections",
            "dir",
            "downloadSpeed",
            "files",
            "gid",
            "infoHash",
            "numPieces",
            "numSeeders",
            "pieceLength",
            "seeder",
            "status",
            "totalLength",
            "uploadLength",
            "uploadSpeed"
        ]
    ]
}
```

**Comment by neverwoodsS** [comment]
> 如下
> 
> ```
> {
>     "jsonrpc": "2.0",
>     "method": "aria2.tellActive",
>     "id": "QXJpYU5nXzE1NTcwNDE5MzdfMC4xMTk5MDc2NTM4NjM5MTE2Nw==",
>     "params": [
>         [
>             "completedLength",
>             "connections",
>             "dir",
>             "downloadSpeed",
>             "files",
>             "gid",
>             "infoHash",
>             "numPieces",
>             "numSeeders",
>             "pieceLength",
>             "seeder",
>             "status",
>             "totalLength",
>             "uploadLength",
>             "uploadSpeed"
>         ]
>     ]
> }
> ```

现已支持，但由于项目重构，需等待其他功能完善后一起发布。
请期待 2.0 版本，我会尽快的。

![](https://user-images.githubusercontent.com/9375375/57828072-ad914500-77dc-11e9-89f7-49113d3e6f99.jpg)
