### ISSUE TITLE
有木有toMap的方法？

### ISSUE THREAD

**Issue by kennenfromchina** [neverwoodsS/idea_flutter_json_format#6]

**Comment by neverwoodsS** [comment]
已添加 toJson 函数，请等待新版本更新。
使用用例：
JsonEncoder().convert(obj)

**Comment by kennenfromchina** [comment]
```dart
/// id : 0
/// name : "string"
/// number : 0
/// price : {"fen":0,"jiao":0,"yuan":0}

class ServiceItemsBean {
  int id;
  String name;
  int number;
  PriceBean price;

  static ServiceItemsBean fromMap(Map<String, dynamic> map) {
    if (map == null) return null;
    ServiceItemsBean serviceItemsBean = ServiceItemsBean();
    serviceItemsBean.id = map['id'];
    serviceItemsBean.name = map['name'];
    serviceItemsBean.number = map['number'];
    serviceItemsBean.price = PriceBean.fromMap(map['price']);
    return serviceItemsBean;
  }

  Map toJson() => {
    "id": id,
    "name": name,
    "number": number,
    "price": price,
  };
}
```
这种嵌套的，toJson方法返回的是对象，不是map了

**Comment by neverwoodsS** [comment]
> ```dart
> ```dart
> /// id : 0
> /// name : "string"
> /// number : 0
> /// price : {"fen":0,"jiao":0,"yuan":0}
> 
> class ServiceItemsBean {
>   int id;
>   String name;
>   int number;
>   PriceBean price;
> 
>   static ServiceItemsBean fromMap(Map<String, dynamic> map) {
>     if (map == null) return null;
>     ServiceItemsBean serviceItemsBean = ServiceItemsBean();
>     serviceItemsBean.id = map['id'];
>     serviceItemsBean.name = map['name'];
>     serviceItemsBean.number = map['number'];
>     serviceItemsBean.price = PriceBean.fromMap(map['price']);
>     return serviceItemsBean;
>   }
> 
>   Map toJson() => {
>     "id": id,
>     "name": name,
>     "number": number,
>     "price": price,
>   };
> }
> ```
> 
> 
> 这种嵌套的，toJson方法返回的是对象，不是map了
> ```dart
> Map toJson() => {
>     "id": id,
>     "name": name,
>     "number": number,
>     "price": price.toJson(),
>   };
> ```
> ```

并不建议直接使用 toJson 函数，而是使用 JsonEncoder。
事实上 toJson 函数也是拿来让 JsonEncoder 使用的。
事实上你本地也应该没有什么需求应该用到 map[key0][key1][key2] 吧，
直接 object.key0.key1.key2 不是更好？
我的理解中需要把对象再转化成 map 主要需求是 object to json 再交给服务端。
这种需求下，JsonEncoder 完全可以胜任了

**Comment by kennenfromchina** [comment]
> > ```dart
> > ```dart
> > /// id : 0
> > /// name : "string"
> > /// number : 0
> > /// price : {"fen":0,"jiao":0,"yuan":0}
> > 
> > class ServiceItemsBean {
> >   int id;
> >   String name;
> >   int number;
> >   PriceBean price;
> > 
> >   static ServiceItemsBean fromMap(Map<String, dynamic> map) {
> >     if (map == null) return null;
> >     ServiceItemsBean serviceItemsBean = ServiceItemsBean();
> >     serviceItemsBean.id = map['id'];
> >     serviceItemsBean.name = map['name'];
> >     serviceItemsBean.number = map['number'];
> >     serviceItemsBean.price = PriceBean.fromMap(map['price']);
> >     return serviceItemsBean;
> >   }
> > 
> >   Map toJson() => {
> >     "id": id,
> >     "name": name,
> >     "number": number,
> >     "price": price,
> >   };
> > }
> > ```
> > 
> > 
> > 这种嵌套的，toJson方法返回的是对象，不是map了
> > ```dart
> > Map toJson() => {
> >     "id": id,
> >     "name": name,
> >     "number": number,
> >     "price": price.toJson(),
> >   };
> > ```
> 
> 并不建议直接使用 toJson 函数，而是使用 JsonEncoder。
> 事实上 toJson 函数也是拿来让 JsonEncoder 使用的。
> 事实上你本地也应该没有什么需求应该用到 map[key0][key1][key2] 吧，
> 直接 object.key0.key1.key2 不是更好？
> 我的理解中需要把对象再转化成 map 主要需求是 object to json 再交给服务端。
> 这种需求下，JsonEncoder 完全可以胜任了

是的，JsonEncoder就可以使用了
