### ISSUE TITLE
快捷键是什么

### ISSUE THREAD

**Issue by WhiteSnowGirl** [neverwoodsS/idea_flutter_json_format#8]
为什么我使用window+N就不行？？？？？？

**Comment by neverwoodsS** [comment]
> 为什么我使用window+N就不行？？？？？？

可以看一下 KeyMap 设置，Generate 是配置的什么快捷键

**Comment by WhiteSnowGirl** [comment]
window同学 请 Keymap 配置里面自定义快捷键
